version: "3.8"

services:

  db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: cupcake-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cupcakes
    ports:
        - 7501:5432
    volumes:
        - ./bin/init.sql:/docker-entrypoint-initdb.d/init.sql